# Generated by Django 3.1.5 on 2021-01-16 23:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_templates', '0002_template_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='content',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Contenido'),
        ),
    ]
