# Generated by Django 3.1.5 on 2021-01-17 10:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_templates', '0003_auto_20210116_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='file',
        ),
        migrations.AlterField(
            model_name='template',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido'),
        ),
    ]
